version: '3.8'
services:
  gateway-api:
    ports:
      - '3000:3000'
    build:
      context: ./
      dockerfile: ./apps/gateway/Dockerfile
    network_mode: 'host'
  postgres-and-api-example-api:
    ports:
      - '3001:3001'
    build:
      context: ./
      dockerfile: ./apps/postgres-and-api-example/Dockerfile
    depends_on:
      - gateway-api
