version: '3.8'
services:
  gateway-api:
    ports:
      - '3000:3000'
    build:
      context: ./
      dockerfile: ./apps/gateway/Dockerfile
    network_mode: 'host'
  nest-js-with-postgres-and-api-api:
    ports:
      - '3001:3001'
    build:
      context: ./
      dockerfile: ./apps/nest-js-with-postgres-and-api/Dockerfile
    depends_on:
      - gateway-api
