version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
      - ./external/database/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    container_name: postgres-postgres-and-api-example
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES="postgres-and-api-example","postgres-and-api-example-test"
