version: '3.8'
services:
  localstack-aws-sqs-and-api-example:
    image: localstack/localstack:latest
    ports:
      - '9330:9330'
    environment:
      - EDGE_PORT=9330
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
