version: '3.8'
services:
  postgres:
    image: postgres:latest
    volumes:
     - ./external/database/multiple-databases.sh:/docker-entrypoint-initdb.d/multiple-databases.sh
    container_name: postgres-nest-js-with-postgres-and-api
    ports:
      - 5432:5432/tcp
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES="nest-js-with-postgres-and-api","nest-js-with-postgres-and-api-test"

